### ISSUE TITLE
Website updaten

### ISSUE THREAD

**Issue by mbruess1** [VeraCologne/aframe-two#10]

**Comment by SoerenTerh** [comment]
Erledigt!

**Comment by mbruess1** [comment]
Ich kann in Firefox (sonst noch nichts getestet) nichts sehen wenn ich ein semester ausgewählt habe :/

**Comment by SoerenTerh** [comment]
Schließe ich, weil ich das zwischenzeitlich erledigt habe. 85b973bf65bd553d64e6b52e254c768986ec7dc6
