### ISSUE TITLE
Kerze ging auf dem Handy nicht

### ISSUE THREAD

**Issue by csteins1** [VeraCologne/aframe-two#102]

**Comment by VeraCologne** [comment]
funktioniert bei mir (Moto G5, Chrome)

**Comment by SoerenTerh** [comment]
#108 Bei mir funktionierts auch. Halt nur nicht gut hinsichtlich der Performance, aber die Funktionalität läuft.

**Comment by mbruess1** [comment]
auch der Ton? Ich meine ich zu erinnern, dass @csteins1 meinte, dass die Animation geht aber der Sound fehlt. Aber sicher bin ich mir da nicht mehr

**Comment by SoerenTerh** [comment]
Ja. Hab es jetzt nochmal ausprobiert. Jetzt funktioniert wirklich der Sound dazu nicht mehr. Die Helligkeit wird aber wie gewohnt gewechselt.

**Comment by SoerenTerh** [comment]
https://github.com/VeraCologne/aframe-two/commit/cbaf81d333839ee8991ad7f7585c7660c0167900

**Comment by csteins1** [comment]
hast du es gefixt?

**Comment by SoerenTerh** [comment]
Ja. Siehe Commit
