### ISSUE TITLE
Bäckereitür: Animation der Tür muss raus

### ISSUE THREAD

**Issue by mbruess1** [VeraCologne/aframe-two#105]
Die Tür lässt User denken, sie können den Laden betreten. Zudem ist die Animation anders gesteuert als die Tür des Tabakladens, die man wirklich nutzen kann

**Comment by SoerenTerh** [comment]
https://github.com/VeraCologne/aframe-two/commit/334e1ef74072721d98b54386c2cc1310e8bb062e
