### ISSUE TITLE
Spiele vereinheitlichen

### ISSUE THREAD

**Issue by mbruess1** [VeraCologne/aframe-two#107]
Memory lässt sich während des spiels wieder minimieren. Die Suchspiele muss man durchspielen. Das sollten wir vereinheitlichen

**Comment by VeraCologne** [comment]
Ich finde das nicht so schlimm, dass Spiele unterschiedlich sind. Das Memory hat ja nichts direkt mit dem Spiel zu tun. Bei den anderen könnte man sich vorstellen, dass man die von der Handlung her unbedingt machen "muss". Außerdem ist das Memory total langweilig, man steht nur davor und bewegt den Kopf :D

**Comment by SoerenTerh** [comment]
Schließe mich da an. Da die zwei Spiele so nah an der Story sind bzw. darauf basieren, sollte man sie dann auch durchspielen. Auch wenn sie nicht die spannensten sind

**Comment by VeraCologne** [comment]
Ich hab aber grad mal in "test" (sorry, ich wollte nur rumspielen, dachte nicht, dass das klappt :D) das Verstecken der Elemente für das Verstecken implementiert. Man kann das Spiel damit verbergen und pausieren, läuft dann danach weiter. Also falls wir es doch nehmen wollen, weil es so einfach war :D

**Comment by SoerenTerh** [comment]
Ergo einfach visible wieder auf false setzen, wenn man das Objekt nochmal anschaut? Warum nicht - hätte ich auch drauf kommen können, dass mans so simple machen könnte :smile:

**Comment by VeraCologne** [comment]
Ja, oder? Also zumindest funktioniert das bei dem Verstecken bei mir, wenn ich nicht total blöd gucke. Das war bei dem Memory so kompliziert, weil ich das Anzeigen nicht von dem "bauen" getrennt hatte, deshalb war ich davon ausgegangen, dass das hier auch so ist :D

**Comment by SoerenTerh** [comment]
Nein. Die Spiele haben wir uns ja sowieso nur zum einmaligen Spielen überlegt. Zumindest zu dem Zeitpunkt, wo ich das als Epic übernommen habe. Und dort hat es einfach so gereicht :smiley:

**Comment by SoerenTerh** [comment]
https://github.com/VeraCologne/aframe-two/commit/3dd9d147bf48172bb41ed56bc29436093b5bf859
