### ISSUE TITLE
Infotextbox auf mobilen Endgeräten testen und ggf. auf diesen verstecken (Timeout?) oder überarbeiten

### ISSUE THREAD

**Issue by mbruess1** [VeraCologne/aframe-two#108]
Infotextbox führt bei OnePlus 3T (Chorme) dazu das alles hängt. Sobald die Box nach mittenlangen versuchen geschlossen weden kann läuft der rest der Aussenzene viel viel flüssiger

**Comment by VeraCologne** [comment]
wie wäre es, wenn wir sie doch invisible machen? Dann läuft die Szene erst mal und wahrscheinlich klickt da ja eh keiner drauf. 

Ich kann leider mobil nicht testen, mein Handy packt das gar nicht, die Szene lädt nicht.

**Comment by VeraCologne** [comment]
Mein Handy packt es doch auf einmal. Funktioniert bei mir (Moto G5 Chrome)

**Comment by SoerenTerh** [comment]
Bei mir funktionierts auch. Halt nur nicht gut hinsichtlich der Performance, aber die Funktionalität läuft.

**Comment by mbruess1** [comment]
Die Performance ist ja gerade das was bei mir nicht funktioniert solange die Tafel angezeigt wird. Wenn man es endlich auf das X schafft kann man sie auch wegklicken und alles ist gut. Nur bis man da ist dauert es Jahrhunderte da wirklich alles vollkommen hängt. Aber okay, wenn das nur bei mir Auftritt, dann können wir das issue schließen ;)

**Comment by SoerenTerh** [comment]
Also. Performance ist nicht gut - aber das hat bei mir, meinem Empfinden nach, weniger mit der Tafel als mehr mit den restlichen Assets zu tun. Bei mir ändert sich performancetechnisch nicht viel, wenn ich die Tafel zu hab :sweat_smile:

**Comment by VeraCologne** [comment]
Ich suche mir morgen jemanden mit nem teuren Handy und teste dann noch mal
:D

**Comment by SoerenTerh** [comment]
Habs mit 'nem Google Pixel ausprobiert. Also wirklich sehr aktuell. Ich glaube, viel mehr optimieren geht nicht mehr, ums überall glatt durchlaufen zu lassen :P

**Comment by SoerenTerh** [comment]
Tafel wird jetzt nach 30s automatisch invisible gemacht. Sollte dementsprechend das Problem etwas lösen. Außerdem noch den einen Triggerpoint etwas verschoben, dass man immer zu der Ausgangsposition vor der Tafel kommen kann.
