### ISSUE TITLE
Junge kommt 2 mal in den Laden einmal mit und einmal ohne Kuchen, nach msix. ist das so gewollt?

### ISSUE THREAD

**Issue by csteins1** [VeraCologne/aframe-two#114]

**Comment by SoerenTerh** [comment]
Ist mir auch aufgefallen. Sieht auch etwas komisch aus, weil er im Grunde nach dem Mal ohne Kuchen plötzlich einmal blinkt und mit dem Kuchen wiederkommt

**Comment by SoerenTerh** [comment]
Gerade nochmal die HTML angeschaut. Das hat damit zu tun, dass die Kuchen beim gleichen Schritt wie die Animation unter die Türschwelle passiert und scheinbar die Visibility erst danach kommt. Und dem Kommentar am Array zufolge gehört das zu der Story, weil sie aus der Bluse fallen!

**Comment by csteins1** [comment]
sieht aber komisch aus

**Comment by csteins1** [comment]
wollen wir das nicht evtl ändern?

**Comment by SoerenTerh** [comment]
Mich stört es nicht, zumal es schwierig ist, das zu visualisieren, dass ihm die Kuchen aus der Bluse fallen. Wenn dir was einfällt, kannst du es gerne anpassen, wie du es dir vorstellst.
