### ISSUE TITLE
manchmal leuchtet Shui Ta beim Sprechen nicht grün auf

### ISSUE THREAD

**Issue by csteins1** [VeraCologne/aframe-two#116]

**Comment by csteins1** [comment]
@mbruess1 @SoerenTerh @VeraCologne beobachtet das mal, habe es jetzt nocheinmal durch und er hat immer geleuchtet.

**Comment by SoerenTerh** [comment]
Komisch. Habe jetzt gerade beim Fixen vom Polizisten drauf geachtet. Da hat er immer schön die Farbe gewechselt und war nie grün, wenn er nicht gesprochen hat :flushed:

**Comment by VeraCologne** [comment]
Ich glaube, hier gibt's ein Missverständnis :D Ich glaube, Cata hat das
Issue erstellt, weil Shui Ta nicht immer geleuchtet hat, wenn er sollte (in
dem Testlauf, wo auch irgendwer irgendwo durch lief, da hing wahrscheinlich
was fest). Und dann hat sie es noch Mal getestet und alles war gut. Also
das Problem war nicht, dass er zu viel geleuchtet hat 😁

**Comment by SoerenTerh** [comment]
Oh okay. Dann können wir das schließen, schätze ich?

**Comment by csteins1** [comment]
genau, ihr solltet die szene nochmal komplett durchgehen und nochmal schauen

**Comment by SoerenTerh** [comment]
Bei mir gabs dazu keine Probleme mehr. Habe beim Testen der anderen Sachen ShuiTa im Auge gehabt. Da lief alles so, wie es sollte.
