### ISSUE TITLE
Zusammenführen der HTML-Dateien

### ISSUE THREAD

**Issue by SoerenTerh** [VeraCologne/aframe-two#19]

**Comment by mbruess1** [comment]
Ich versuche das physics zeug nächste Woche nochmal und ergänze den rest

**Comment by SoerenTerh** [comment]
#24 depends on #19

**Comment by mbruess1** [comment]
grötenteils in https://github.com/VeraCologne/aframe-two/tree/mixAndMatch gelöst. siehe Commit message bezütlich noch vorhandener bugs

**Comment by VeraCologne** [comment]
Tür-öffnen-Event
Höhe der Kamera außen
Größe der beiden Szenen
XML-Fehler im Tabakladen-Model

**Comment by mbruess1** [comment]
@SoerenTerh könntest du nochmal nach dem TAbakladen_model fehler finden? 👼

**Comment by SoerenTerh** [comment]
Wenn man sich das rawgit von der Branch anschaut, gibts kein Problem und das Modell des Ladens lässt sich ohne Probleme laden.

**Comment by mbruess1** [comment]
Mit commit 1c91a128dcf8664ffc97153ae5d2ede275f6b39e nun lauffähig und könnte zu develop gemacht werden, wenn jeder (@SoerenTerh @VeraCologne @csteins1 @nzipse) nochmals getestet hat
