### ISSUE TITLE
Spielaufruf

### ISSUE THREAD

**Issue by SoerenTerh** [VeraCologne/aframe-two#21]
Spiel kann gespielt werden, wenn Junge nicht im Laden ist

- Junge spricht einen an, ob man das Spiel spielen möchte

- Spielen möglich, wenn man von selbst nach draußen geht in entsprechendem Zeitraum

**Comment by csteins1** [comment]
+Spielaufruf Tisch

**Comment by SoerenTerh** [comment]
#23

**Comment by SoerenTerh** [comment]
Depends on #19

**Comment by SoerenTerh** [comment]
Spielaufruf durch Kuchen auf dem Tisch
