### ISSUE TITLE
Randomisierung der Positionen der Kuchen vs. hardcoded Positionen

### ISSUE THREAD

**Issue by SoerenTerh** [VeraCologne/aframe-two#23]
Assignee entscheidet sich, wie es gelöst werden soll.

**Comment by SoerenTerh** [comment]
Mache ich nach der Spiellogik

**Comment by csteins1** [comment]
Wäre es möglich, dass die Kuchen nicht so nah aneinander spawnen? 
Könntest du das Feld auf die Außenfläche erweitern, aber aufpassen, dass diese nicht in den Häusern spawnen?

**Comment by SoerenTerh** [comment]
Wenn's auf die jetztige Art und Weise nicht okay ist, wirds nur mit unverhältnismäßigem Mehraufwand umsetzbar sein. Ich close das erstmal.
