### ISSUE TITLE
Musik: Sieben Elefanten 

### ISSUE THREAD

**Issue by SoerenTerh** [VeraCologne/aframe-two#32]
Kann man das Lied vom Schauspielhaus gestellt bekommen, um es in die Szene einbinden zu können. Bspw. Radio

**Comment by mbruess1** [comment]
BILD- UND VIDEOMATERIAL / TECHNISCHE PROBLEME
Kristina Rein
Öffentlichkeitsarbeit und Onlineredaktion
SCHAUSPIEL KÖLN
Schanzenstrasse 6 - 20
51063 Köln
Telefon: 0221 | 221 27314
Telefax: 0221 | 221 28367
Mobil: 0152 | 54588888
E-Mail: kristina.rein@schauspiel.koeln

**Comment by VeraCologne** [comment]
https://youtu.be/3qAzIE53ER0

**Comment by mbruess1** [comment]
Anfrage an Schauspiel Köln ist raus

**Comment by mbruess1** [comment]
blocked by Schauspiel Köln
