### ISSUE TITLE
Vertonung des Großvaters

### ISSUE THREAD

**Issue by csteins1** [VeraCologne/aframe-two#49]

**Comment by csteins1** [comment]
Textvorschlag: 
"Guten Tag!
Na, das gute alte Memory. Spiel doch eine Runde und decke die verschiedenen Bildpaare auf."

ok?
@VeraCologne @SoerenTerh @mbruess1

**Comment by VeraCologne** [comment]
find ich gut :)

**Comment by SoerenTerh** [comment]
Ich auch!
