### ISSUE TITLE
Das Ausschalten der Dinge von Außen, wenn man in die Szene wechselt

### ISSUE THREAD

**Issue by csteins1** [VeraCologne/aframe-two#71]
spiele, regen, spielsachen, memory, der kuchen und die figure. Also alle Spiele eigentlich ausschalten
Zwitschern ebenso ausschalten

**Comment by SoerenTerh** [comment]
https://github.com/VeraCologne/aframe-two/commit/15d88fd6740b0578e51b50091f561ccab4bd36ac
done
