### ISSUE TITLE
Triggerpoints innen uns außen stimmen nicht

### ISSUE THREAD

**Issue by mbruess1** [VeraCologne/aframe-two#76]
Triggerpoints führen bei triggern nicht direkt unter den punkt sondern irgendwo ungefähr in die richtung. Das führt zu einer totalen orientierungslosigkeit nach dem benutzen eines Triggerpoints

**Comment by mbruess1** [comment]
der triggerpoint vor dem tisch läst einen nicht die spiele aufrufen

**Comment by VeraCologne** [comment]
sollte jetzt funktionieren
