### ISSUE TITLE
Poligone prüfen

### ISSUE THREAD

**Issue by mbruess1** [VeraCologne/aframe-two#8]

**Comment by VeraCologne** [comment]
bei den Häusern sind jetzt die ganzen überflüssigen Linien raus. Bei der Tür vom Tabakladen hat das die nicht kleiner gemacht, also lasse ich die vom Bäcker jetzt erst mal so. Mein Teil ist damit fertig.

**Comment by SoerenTerh** [comment]
Bei meinem Modellen, wo das problematisch war, habe ich nachgearbeitet!

**Comment by mbruess1** [comment]
Ich habe meine jetzt auch alle verkleinert. Das heißt, das habe ich so weit es ging ohne Löcher zu bekommen. Zudem habe ich auch mal alle mp3 files durch ein comprimierungsprogramm laufen lassen
