### ISSUE TITLE
Menschen verschwinden lassen

### ISSUE THREAD

**Issue by VeraCologne** [VeraCologne/aframe-two#81]
Sollen Menschen, die nach draußen gehen, irgendwann unsichtbar werden oder lassen wir die einfach da rumstehen?

**Comment by mbruess1** [comment]
ich habe gerstern mal alles bis zum ende durchlaufen lassen und mag es eigenlich wie die dann am ende da alle rumstehen ;) Klar ist es nicht an die aussenzene angepasst. Aber das können wir ja unter Ideen für den weiteren Projektverlauf schieben

**Comment by VeraCologne** [comment]
warum steht das in Review? Ich bin auch einverstanden mit draußen rumstehen lassen.

**Comment by mbruess1** [comment]
damit du mein kommentar liest und entscheiden kannst ob dir das reicht um es zu schließen ;)

**Comment by VeraCologne** [comment]
Aaah ok, ich dachte, dein Kommentar war für die anderen bestimmt. Ich fand
das ja eh gut, die da rumstehen zu lassen. Dann schließe ich das mal :)
