### ISSUE TITLE
Rechnung ist von unten durchsichtig

### ISSUE THREAD

**Issue by VeraCologne** [VeraCologne/aframe-two#84]

**Comment by mbruess1** [comment]
Ich kann den Rechnungen leider keine 3D Körper verpassen. Jeder Versuch endet damit, dass der Schriftzug "Rechnung" nicht mehr korrekt gerendert wird und man somit nicht mehr erkennt, das es sich hier um eine Rechnung handelt. 
@SoerenTerh Die rechnungen waren von dir, oder? Hast du eine idee woran das liegen könnte?

**Comment by SoerenTerh** [comment]
https://github.com/VeraCologne/aframe-two/commit/fc5612aa69c49aeeb333a0b6676c8b41db1ce0a7
Blöd, wenn man Planes für die Modelle benutzt. Habe sie jetzt mal durch Boxes mit extrem geringer Tiefe ausgetauscht. Jetzt sind sie auch vernünftig sichtbar. Auch von hinten
