### ISSUE TITLE
Wartefunktion Sound bei Zigarette aufsammeln

### ISSUE THREAD

**Issue by VeraCologne** [VeraCologne/aframe-two#85]

**Comment by mbruess1** [comment]
Kann ich leider nicht bearbeiten, da der event listener von aframe nicht reagiert, da wir die audiodatei ja wegen den problemen letzte Woche über HTML5 und nicht aframe aufrufen.

**Comment by SoerenTerh** [comment]
Ez hacky way: https://github.com/VeraCologne/aframe-two/commit/8f3cb8dd45a95b7b1e49ccf7ffdd9f5b39ce0bc5
Lasse jetzt einfach per Timeout abwarten, bis effektiv die mp3-Länge abgelaufen ist :tiger:
