### ISSUE TITLE
Shui Ta und Schreiner werden nicht mehr visible bei "two"

### ISSUE THREAD

**Issue by VeraCologne** [VeraCologne/aframe-two#95]
Habe sie jetzt erst mal komplett visible gemacht, falls wir das event nicht gefixt bekommen

**Comment by SoerenTerh** [comment]
Hatten 'ne Dopplung bei ShuiTa im Modell. Da hatte sowohl der Container, als auch das Modell das Event. Bei mir läufts jetzt so.
