### ISSUE TITLE
Schreiner läuft durch Mann beim Stellage zur Tür stellen

### ISSUE THREAD

**Issue by VeraCologne** [VeraCologne/aframe-two#96]

**Comment by VeraCologne** [comment]
habe versucht, den Mann zusammen mit der Frau in vEleven aus dem Weg zu räumen, weiß aber nicht, ob das funktioniert hat

**Comment by SoerenTerh** [comment]
Nachgeschaut - ist super so. Platz dazwischen ist genug!
