### ISSUE TITLE
Shui Ta läuft nicht weit genug nach vorne beim Betten wegräumen

### ISSUE THREAD

**Issue by VeraCologne** [VeraCologne/aframe-two#99]

**Comment by csteins1** [comment]
wenn er weiter laufen würde, dann würde er doch in die Figuren rennen? 
an das letzte bett kommt er doch ran oder meinst du/ihr nicht?

**Comment by VeraCologne** [comment]
Es kann sein, dass ich was falsches auskommentiert hatte hier und er doch
richtig läuft. Wenn du das so passend findest, dann schließ das Issue
ruhig, das ist im Chaos entstanden :D

**Comment by csteins1** [comment]
Ich finde es in Ordnung so. Schande über mei Haupt, wenn die 2 anderen es nicht gut finden. Wird geschlossen und ansonsten (falls es überhaupt auffällt) muss es halt geändert werden.
